import { Inter } from 'next/font/google'
import { HeaderUser } from '@/components/header/header-user'
import type { Metadata } from 'next'
import '../globals.css'
import { Footer } from '@/components/footer'
import Avaliações from './avaliacoes/page'
import AvaliaçãoCliente from './avaliacaoCliente/page'
import LinkAvaliações from './linkAvaliacoes/page'
import { Red_Hat_Display } from 'next/font/google' 
import { cn } from '@/lib/utils'
import { CartProvider } from '@/providers/cart'
import InternalAppLayout from '@/components/internal-app-layout'

const redHatDisplay = Red_Hat_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function AppLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={cn('min-h-screen', redHatDisplay.className)}>
        <InternalAppLayout>
          {children}
        </InternalAppLayout>
      </body>
    </html>
  )
}
